//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/AR Input Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ARInputActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ARInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""AR Input Actions"",
    ""maps"": [
        {
            ""name"": ""XRI UI"",
            ""id"": ""edd65a7c-601c-4915-8307-025a081d8790"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c9a92aca-49d5-4910-8ade-8e994f0a31f0"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""eba98c2e-6268-4233-bb88-946287bc753c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""448b396b-0885-4543-ac5a-8b3405da6791"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""682022c0-857a-4332-8753-7f8fcdf84d37"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""b194cd98-7e4f-457a-a60c-cebc25dc32a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""bd7fc534-75e3-489d-94fb-3d45cb78d8f3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""cc5f5666-a75c-4dfc-8566-ded8ec9b4ae3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""533aeb95-18b2-4a83-a69d-f6e0be72ff8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e87fa299-8441-4620-89dd-0564c7d552e2"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""445a013e-9c17-48a2-9856-067e4826df03"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05c1e38e-79dd-41cb-95d5-74f42e65d92f"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57909bb4-1088-4975-9227-ecc87a305257"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2740386d-d4b6-4342-903c-d9390783f04a"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d6fd3bb5-c747-4eba-b599-1c6d7c738e2a"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fb2286cc-fa20-4564-bff6-9f790f12cf6b"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54eb7da2-546a-4d75-bfcc-ae38be303a59"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Gamepad"",
                    ""id"": ""4c9a5170-d325-45ee-8ef9-fc12d1f5a97e"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""c846c708-b27e-4ac9-9a83-c80ac5c263d5"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""caf2fb01-3e95-47c1-8663-315057149d48"",
                    ""path"": ""<Gamepad>/rightStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""830d65e9-887d-45b4-8386-562deb29e465"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""e5c71442-9909-46d8-aa56-8fa3574a8227"",
                    ""path"": ""<Gamepad>/rightStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""210246e8-c3c4-4edc-be9c-1916858346df"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""fb701ef0-9910-4639-80d1-2c1c03f871ed"",
                    ""path"": ""<Gamepad>/rightStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3de9f409-fb44-4311-8705-b4f4e7cd3029"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""bd001ba1-d6a2-4a97-9c87-36b5b92728af"",
                    ""path"": ""<Gamepad>/rightStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fcc0a2cd-a126-43ad-bb1e-ffc1ae7668c7"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Joystick"",
                    ""id"": ""65cbb13a-6e00-4973-9887-e49e06575091"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3c5803e2-42d0-4d48-bbd6-41ce4442df0b"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d5b1219c-0df6-4bc5-ad11-205b748cade4"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""065d2394-f10a-46df-b6cb-2c56a6c842ea"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""29921809-7785-44a1-a316-e96307174552"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""49817cc8-fecc-406d-a187-6393de317e95"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""ef33431d-17d0-4e1c-90f2-bbaa2ef9a8b7"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""5ddfdce2-0f11-4f4e-8931-0ae6fb289ac7"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""5ceab4e0-1600-4bfb-acf6-8d02c4e10aea"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""94e10d8b-5bfa-439d-afae-b975efac2b7b"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9fc7d14a-385d-4ca5-b185-906e049b7eed"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d7e5e0c4-05dc-4f2f-8649-a66fe843caed"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""76ab9656-e168-4b2c-9a6b-d8d6da981e4f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ad7bc5b3-6ada-42a2-9cba-5c7334cba7be"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9f2a7c29-a588-4b6a-a966-955eb408c526"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""67f51768-1493-4444-b118-82d398a16fdd"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""198e6869-709e-448d-96d4-27186c9d56e6"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Touchscreen Gestures"",
            ""id"": ""6fb00339-a75a-4e5b-94e0-839f979f2a8a"",
            ""actions"": [
                {
                    ""name"": ""Tap Start Position"",
                    ""type"": ""Value"",
                    ""id"": ""0f53f821-ec5d-472c-bd12-fb5ce515ae59"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Drag Current Position"",
                    ""type"": ""Value"",
                    ""id"": ""07fd51be-2a34-4531-939c-ff750fcf8e4d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Drag Delta"",
                    ""type"": ""Value"",
                    ""id"": ""ccd1d49f-8e5b-4c66-8d2c-fb774934270b"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pinch Start Position"",
                    ""type"": ""Value"",
                    ""id"": ""07f4446a-0f0c-4176-a67e-75be05a3be3c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pinch Gap"",
                    ""type"": ""Value"",
                    ""id"": ""c299ab55-2420-4eb1-a459-0af3846471b9"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pinch Gap Delta"",
                    ""type"": ""Value"",
                    ""id"": ""d1d816b2-4bec-4393-bf83-a59146ee0abc"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Twist Start Position"",
                    ""type"": ""Value"",
                    ""id"": ""e476e037-f414-4b6d-ac4a-486d7228ec43"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Twist Delta Rotation"",
                    ""type"": ""Value"",
                    ""id"": ""5910a9c0-4a90-4a2c-92cb-e33054cfd463"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Screen Touch Count"",
                    ""type"": ""Value"",
                    ""id"": ""c1e4b6b1-d82a-485c-9d29-9d42e48df255"",
                    ""expectedControlType"": ""Integer"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Press"",
                    ""type"": ""Button"",
                    ""id"": ""133f6429-3af9-4dcf-ba78-766dd8af0cab"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1df03dbf-eebe-472e-af83-474c8022dba4"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap Start Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9614dc99-2437-401a-a005-770bb98c4ad0"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Tap Start Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eb175a82-fad6-4249-bc9f-a6c9acee4436"",
                    ""path"": ""<TouchscreenGestureInputController>/dragCurrentPosition"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag Current Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""One Modifier"",
                    ""id"": ""2648faca-8c9b-4bcd-9653-fc9cfa39dbe3"",
                    ""path"": ""OneModifier"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag Current Position"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""modifier"",
                    ""id"": ""1f42a89b-32be-49d7-8153-507ff950cb3b"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag Current Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""binding"",
                    ""id"": ""7e88eed9-d5b6-4c3a-9dd7-ac83c45fced3"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag Current Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""40fc89b1-2773-4288-b02f-892fea9b7d48"",
                    ""path"": ""<TouchscreenGestureInputController>/twistDeltaRotation"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Twist Delta Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d919e652-0e4a-4f12-a1f9-b18cead206e2"",
                    ""path"": ""<TouchscreenGestureInputController>/fingerCount"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Screen Touch Count"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""044d4cc1-3ad7-4d38-a95f-994badd7e1a3"",
                    ""path"": ""<TouchscreenGestureInputController>/dragDelta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Drag Delta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9e3b31e7-2f82-40f3-bfe1-ad0fa7f035d4"",
                    ""path"": ""<TouchscreenGestureInputController>/pinchStartPosition1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pinch Start Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3092672-a026-446d-8bb6-44843db135b1"",
                    ""path"": ""<TouchscreenGestureInputController>/pinchGapDelta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pinch Gap Delta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0f8550ed-7261-48e0-aa0e-6670f29141f5"",
                    ""path"": ""<TouchscreenGestureInputController>/twistStartPosition1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Twist Start Position"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4f94c62c-7c6d-4547-82fe-b6ed10da8388"",
                    ""path"": ""<TouchscreenGestureInputController>/pinchGap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pinch Gap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d95aecd8-f284-4c0d-afe3-9688ea2667c8"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b318e537-3319-469a-a1f5-4f3c06bc4f27"",
                    ""path"": ""<Mouse>/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Press"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Generic XR Controller"",
            ""bindingGroup"": ""Generic XR Controller"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>{LeftHand}"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>{RightHand}"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>"",
                    ""isOptional"": true,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<WMRHMD>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Continuous Move"",
            ""bindingGroup"": ""Continuous Move"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>{LeftHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>{RightHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Noncontinuous Move"",
            ""bindingGroup"": ""Noncontinuous Move"",
            ""devices"": [
                {
                    ""devicePath"": ""<XRController>{LeftHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<XRController>{RightHand}"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // XRI UI
        m_XRIUI = asset.FindActionMap("XRI UI", throwIfNotFound: true);
        m_XRIUI_Navigate = m_XRIUI.FindAction("Navigate", throwIfNotFound: true);
        m_XRIUI_Submit = m_XRIUI.FindAction("Submit", throwIfNotFound: true);
        m_XRIUI_Cancel = m_XRIUI.FindAction("Cancel", throwIfNotFound: true);
        m_XRIUI_Point = m_XRIUI.FindAction("Point", throwIfNotFound: true);
        m_XRIUI_Click = m_XRIUI.FindAction("Click", throwIfNotFound: true);
        m_XRIUI_ScrollWheel = m_XRIUI.FindAction("ScrollWheel", throwIfNotFound: true);
        m_XRIUI_MiddleClick = m_XRIUI.FindAction("MiddleClick", throwIfNotFound: true);
        m_XRIUI_RightClick = m_XRIUI.FindAction("RightClick", throwIfNotFound: true);
        // Touchscreen Gestures
        m_TouchscreenGestures = asset.FindActionMap("Touchscreen Gestures", throwIfNotFound: true);
        m_TouchscreenGestures_TapStartPosition = m_TouchscreenGestures.FindAction("Tap Start Position", throwIfNotFound: true);
        m_TouchscreenGestures_DragCurrentPosition = m_TouchscreenGestures.FindAction("Drag Current Position", throwIfNotFound: true);
        m_TouchscreenGestures_DragDelta = m_TouchscreenGestures.FindAction("Drag Delta", throwIfNotFound: true);
        m_TouchscreenGestures_PinchStartPosition = m_TouchscreenGestures.FindAction("Pinch Start Position", throwIfNotFound: true);
        m_TouchscreenGestures_PinchGap = m_TouchscreenGestures.FindAction("Pinch Gap", throwIfNotFound: true);
        m_TouchscreenGestures_PinchGapDelta = m_TouchscreenGestures.FindAction("Pinch Gap Delta", throwIfNotFound: true);
        m_TouchscreenGestures_TwistStartPosition = m_TouchscreenGestures.FindAction("Twist Start Position", throwIfNotFound: true);
        m_TouchscreenGestures_TwistDeltaRotation = m_TouchscreenGestures.FindAction("Twist Delta Rotation", throwIfNotFound: true);
        m_TouchscreenGestures_ScreenTouchCount = m_TouchscreenGestures.FindAction("Screen Touch Count", throwIfNotFound: true);
        m_TouchscreenGestures_Press = m_TouchscreenGestures.FindAction("Press", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // XRI UI
    private readonly InputActionMap m_XRIUI;
    private List<IXRIUIActions> m_XRIUIActionsCallbackInterfaces = new List<IXRIUIActions>();
    private readonly InputAction m_XRIUI_Navigate;
    private readonly InputAction m_XRIUI_Submit;
    private readonly InputAction m_XRIUI_Cancel;
    private readonly InputAction m_XRIUI_Point;
    private readonly InputAction m_XRIUI_Click;
    private readonly InputAction m_XRIUI_ScrollWheel;
    private readonly InputAction m_XRIUI_MiddleClick;
    private readonly InputAction m_XRIUI_RightClick;
    public struct XRIUIActions
    {
        private @ARInputActions m_Wrapper;
        public XRIUIActions(@ARInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_XRIUI_Navigate;
        public InputAction @Submit => m_Wrapper.m_XRIUI_Submit;
        public InputAction @Cancel => m_Wrapper.m_XRIUI_Cancel;
        public InputAction @Point => m_Wrapper.m_XRIUI_Point;
        public InputAction @Click => m_Wrapper.m_XRIUI_Click;
        public InputAction @ScrollWheel => m_Wrapper.m_XRIUI_ScrollWheel;
        public InputAction @MiddleClick => m_Wrapper.m_XRIUI_MiddleClick;
        public InputAction @RightClick => m_Wrapper.m_XRIUI_RightClick;
        public InputActionMap Get() { return m_Wrapper.m_XRIUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(XRIUIActions set) { return set.Get(); }
        public void AddCallbacks(IXRIUIActions instance)
        {
            if (instance == null || m_Wrapper.m_XRIUIActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_XRIUIActionsCallbackInterfaces.Add(instance);
            @Navigate.started += instance.OnNavigate;
            @Navigate.performed += instance.OnNavigate;
            @Navigate.canceled += instance.OnNavigate;
            @Submit.started += instance.OnSubmit;
            @Submit.performed += instance.OnSubmit;
            @Submit.canceled += instance.OnSubmit;
            @Cancel.started += instance.OnCancel;
            @Cancel.performed += instance.OnCancel;
            @Cancel.canceled += instance.OnCancel;
            @Point.started += instance.OnPoint;
            @Point.performed += instance.OnPoint;
            @Point.canceled += instance.OnPoint;
            @Click.started += instance.OnClick;
            @Click.performed += instance.OnClick;
            @Click.canceled += instance.OnClick;
            @ScrollWheel.started += instance.OnScrollWheel;
            @ScrollWheel.performed += instance.OnScrollWheel;
            @ScrollWheel.canceled += instance.OnScrollWheel;
            @MiddleClick.started += instance.OnMiddleClick;
            @MiddleClick.performed += instance.OnMiddleClick;
            @MiddleClick.canceled += instance.OnMiddleClick;
            @RightClick.started += instance.OnRightClick;
            @RightClick.performed += instance.OnRightClick;
            @RightClick.canceled += instance.OnRightClick;
        }

        private void UnregisterCallbacks(IXRIUIActions instance)
        {
            @Navigate.started -= instance.OnNavigate;
            @Navigate.performed -= instance.OnNavigate;
            @Navigate.canceled -= instance.OnNavigate;
            @Submit.started -= instance.OnSubmit;
            @Submit.performed -= instance.OnSubmit;
            @Submit.canceled -= instance.OnSubmit;
            @Cancel.started -= instance.OnCancel;
            @Cancel.performed -= instance.OnCancel;
            @Cancel.canceled -= instance.OnCancel;
            @Point.started -= instance.OnPoint;
            @Point.performed -= instance.OnPoint;
            @Point.canceled -= instance.OnPoint;
            @Click.started -= instance.OnClick;
            @Click.performed -= instance.OnClick;
            @Click.canceled -= instance.OnClick;
            @ScrollWheel.started -= instance.OnScrollWheel;
            @ScrollWheel.performed -= instance.OnScrollWheel;
            @ScrollWheel.canceled -= instance.OnScrollWheel;
            @MiddleClick.started -= instance.OnMiddleClick;
            @MiddleClick.performed -= instance.OnMiddleClick;
            @MiddleClick.canceled -= instance.OnMiddleClick;
            @RightClick.started -= instance.OnRightClick;
            @RightClick.performed -= instance.OnRightClick;
            @RightClick.canceled -= instance.OnRightClick;
        }

        public void RemoveCallbacks(IXRIUIActions instance)
        {
            if (m_Wrapper.m_XRIUIActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IXRIUIActions instance)
        {
            foreach (var item in m_Wrapper.m_XRIUIActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_XRIUIActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public XRIUIActions @XRIUI => new XRIUIActions(this);

    // Touchscreen Gestures
    private readonly InputActionMap m_TouchscreenGestures;
    private List<ITouchscreenGesturesActions> m_TouchscreenGesturesActionsCallbackInterfaces = new List<ITouchscreenGesturesActions>();
    private readonly InputAction m_TouchscreenGestures_TapStartPosition;
    private readonly InputAction m_TouchscreenGestures_DragCurrentPosition;
    private readonly InputAction m_TouchscreenGestures_DragDelta;
    private readonly InputAction m_TouchscreenGestures_PinchStartPosition;
    private readonly InputAction m_TouchscreenGestures_PinchGap;
    private readonly InputAction m_TouchscreenGestures_PinchGapDelta;
    private readonly InputAction m_TouchscreenGestures_TwistStartPosition;
    private readonly InputAction m_TouchscreenGestures_TwistDeltaRotation;
    private readonly InputAction m_TouchscreenGestures_ScreenTouchCount;
    private readonly InputAction m_TouchscreenGestures_Press;
    public struct TouchscreenGesturesActions
    {
        private @ARInputActions m_Wrapper;
        public TouchscreenGesturesActions(@ARInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @TapStartPosition => m_Wrapper.m_TouchscreenGestures_TapStartPosition;
        public InputAction @DragCurrentPosition => m_Wrapper.m_TouchscreenGestures_DragCurrentPosition;
        public InputAction @DragDelta => m_Wrapper.m_TouchscreenGestures_DragDelta;
        public InputAction @PinchStartPosition => m_Wrapper.m_TouchscreenGestures_PinchStartPosition;
        public InputAction @PinchGap => m_Wrapper.m_TouchscreenGestures_PinchGap;
        public InputAction @PinchGapDelta => m_Wrapper.m_TouchscreenGestures_PinchGapDelta;
        public InputAction @TwistStartPosition => m_Wrapper.m_TouchscreenGestures_TwistStartPosition;
        public InputAction @TwistDeltaRotation => m_Wrapper.m_TouchscreenGestures_TwistDeltaRotation;
        public InputAction @ScreenTouchCount => m_Wrapper.m_TouchscreenGestures_ScreenTouchCount;
        public InputAction @Press => m_Wrapper.m_TouchscreenGestures_Press;
        public InputActionMap Get() { return m_Wrapper.m_TouchscreenGestures; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchscreenGesturesActions set) { return set.Get(); }
        public void AddCallbacks(ITouchscreenGesturesActions instance)
        {
            if (instance == null || m_Wrapper.m_TouchscreenGesturesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TouchscreenGesturesActionsCallbackInterfaces.Add(instance);
            @TapStartPosition.started += instance.OnTapStartPosition;
            @TapStartPosition.performed += instance.OnTapStartPosition;
            @TapStartPosition.canceled += instance.OnTapStartPosition;
            @DragCurrentPosition.started += instance.OnDragCurrentPosition;
            @DragCurrentPosition.performed += instance.OnDragCurrentPosition;
            @DragCurrentPosition.canceled += instance.OnDragCurrentPosition;
            @DragDelta.started += instance.OnDragDelta;
            @DragDelta.performed += instance.OnDragDelta;
            @DragDelta.canceled += instance.OnDragDelta;
            @PinchStartPosition.started += instance.OnPinchStartPosition;
            @PinchStartPosition.performed += instance.OnPinchStartPosition;
            @PinchStartPosition.canceled += instance.OnPinchStartPosition;
            @PinchGap.started += instance.OnPinchGap;
            @PinchGap.performed += instance.OnPinchGap;
            @PinchGap.canceled += instance.OnPinchGap;
            @PinchGapDelta.started += instance.OnPinchGapDelta;
            @PinchGapDelta.performed += instance.OnPinchGapDelta;
            @PinchGapDelta.canceled += instance.OnPinchGapDelta;
            @TwistStartPosition.started += instance.OnTwistStartPosition;
            @TwistStartPosition.performed += instance.OnTwistStartPosition;
            @TwistStartPosition.canceled += instance.OnTwistStartPosition;
            @TwistDeltaRotation.started += instance.OnTwistDeltaRotation;
            @TwistDeltaRotation.performed += instance.OnTwistDeltaRotation;
            @TwistDeltaRotation.canceled += instance.OnTwistDeltaRotation;
            @ScreenTouchCount.started += instance.OnScreenTouchCount;
            @ScreenTouchCount.performed += instance.OnScreenTouchCount;
            @ScreenTouchCount.canceled += instance.OnScreenTouchCount;
            @Press.started += instance.OnPress;
            @Press.performed += instance.OnPress;
            @Press.canceled += instance.OnPress;
        }

        private void UnregisterCallbacks(ITouchscreenGesturesActions instance)
        {
            @TapStartPosition.started -= instance.OnTapStartPosition;
            @TapStartPosition.performed -= instance.OnTapStartPosition;
            @TapStartPosition.canceled -= instance.OnTapStartPosition;
            @DragCurrentPosition.started -= instance.OnDragCurrentPosition;
            @DragCurrentPosition.performed -= instance.OnDragCurrentPosition;
            @DragCurrentPosition.canceled -= instance.OnDragCurrentPosition;
            @DragDelta.started -= instance.OnDragDelta;
            @DragDelta.performed -= instance.OnDragDelta;
            @DragDelta.canceled -= instance.OnDragDelta;
            @PinchStartPosition.started -= instance.OnPinchStartPosition;
            @PinchStartPosition.performed -= instance.OnPinchStartPosition;
            @PinchStartPosition.canceled -= instance.OnPinchStartPosition;
            @PinchGap.started -= instance.OnPinchGap;
            @PinchGap.performed -= instance.OnPinchGap;
            @PinchGap.canceled -= instance.OnPinchGap;
            @PinchGapDelta.started -= instance.OnPinchGapDelta;
            @PinchGapDelta.performed -= instance.OnPinchGapDelta;
            @PinchGapDelta.canceled -= instance.OnPinchGapDelta;
            @TwistStartPosition.started -= instance.OnTwistStartPosition;
            @TwistStartPosition.performed -= instance.OnTwistStartPosition;
            @TwistStartPosition.canceled -= instance.OnTwistStartPosition;
            @TwistDeltaRotation.started -= instance.OnTwistDeltaRotation;
            @TwistDeltaRotation.performed -= instance.OnTwistDeltaRotation;
            @TwistDeltaRotation.canceled -= instance.OnTwistDeltaRotation;
            @ScreenTouchCount.started -= instance.OnScreenTouchCount;
            @ScreenTouchCount.performed -= instance.OnScreenTouchCount;
            @ScreenTouchCount.canceled -= instance.OnScreenTouchCount;
            @Press.started -= instance.OnPress;
            @Press.performed -= instance.OnPress;
            @Press.canceled -= instance.OnPress;
        }

        public void RemoveCallbacks(ITouchscreenGesturesActions instance)
        {
            if (m_Wrapper.m_TouchscreenGesturesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITouchscreenGesturesActions instance)
        {
            foreach (var item in m_Wrapper.m_TouchscreenGesturesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TouchscreenGesturesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TouchscreenGesturesActions @TouchscreenGestures => new TouchscreenGesturesActions(this);
    private int m_GenericXRControllerSchemeIndex = -1;
    public InputControlScheme GenericXRControllerScheme
    {
        get
        {
            if (m_GenericXRControllerSchemeIndex == -1) m_GenericXRControllerSchemeIndex = asset.FindControlSchemeIndex("Generic XR Controller");
            return asset.controlSchemes[m_GenericXRControllerSchemeIndex];
        }
    }
    private int m_ContinuousMoveSchemeIndex = -1;
    public InputControlScheme ContinuousMoveScheme
    {
        get
        {
            if (m_ContinuousMoveSchemeIndex == -1) m_ContinuousMoveSchemeIndex = asset.FindControlSchemeIndex("Continuous Move");
            return asset.controlSchemes[m_ContinuousMoveSchemeIndex];
        }
    }
    private int m_NoncontinuousMoveSchemeIndex = -1;
    public InputControlScheme NoncontinuousMoveScheme
    {
        get
        {
            if (m_NoncontinuousMoveSchemeIndex == -1) m_NoncontinuousMoveSchemeIndex = asset.FindControlSchemeIndex("Noncontinuous Move");
            return asset.controlSchemes[m_NoncontinuousMoveSchemeIndex];
        }
    }
    public interface IXRIUIActions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
    }
    public interface ITouchscreenGesturesActions
    {
        void OnTapStartPosition(InputAction.CallbackContext context);
        void OnDragCurrentPosition(InputAction.CallbackContext context);
        void OnDragDelta(InputAction.CallbackContext context);
        void OnPinchStartPosition(InputAction.CallbackContext context);
        void OnPinchGap(InputAction.CallbackContext context);
        void OnPinchGapDelta(InputAction.CallbackContext context);
        void OnTwistStartPosition(InputAction.CallbackContext context);
        void OnTwistDeltaRotation(InputAction.CallbackContext context);
        void OnScreenTouchCount(InputAction.CallbackContext context);
        void OnPress(InputAction.CallbackContext context);
    }
}
